// site3/site-vue/src/App.vue
<template>
  <div>
     <HeaderCont attr="header__wrap SebangGothic4 bg-blue"/>
     <router-view/>
     <FooterCont attr="footer__wrap SebangGothic4 section bg-blue"/>
  </div>
 </template>

<script>
import HeaderCont from '@/components/HeaderCont.vue'
import FooterCont from '@/components/FooterCont.vue'

export default ({
  components: {
    HeaderCont,
    FooterCont
  }
})
</script>

<style lang="scss">
  @import "index.scss"
</style>

// site3/site-react/src/App.js
import React from 'react';
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import Header from './components/layout/Header';
import Footer from './components/layout/Footer';
import Home from './components/pages/Home';
import Member from './components/pages/Member';
import Port from './components/pages/Port';
import Youtube from './components/pages/Youtube';
import Unsplash from './components/pages/Unsplash';
import Movie from './components/pages/Movie';

function App() {
  return (
    <BrowserRouter>
      <Header attr={['header__wrap', 'SebangGothic4', 'bg-blue']} />
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/member" element={<Member />} />
        <Route path="/port" element={<Port />} />
        <Route path="/youtube" element={<Youtube />} />
        <Route path="/unsplash" element={<Unsplash />} />
        <Route path="/movie" element={<Movie />} />
      </Routes>
      <Footer attr={'footer__wrap SebangGothic4 section bg-blue'} />
    </BrowserRouter>
  );
}

export default App;
